### PR TITLE
Laravel pint codestyle

### PR DESCRIPTION
**Pull request by josefbehr**

### CODE REVIEW

**Comment by cheesegrits** [comment]
Can you accommodate one strong personal preference of mine, which is what PHP Storm calls "Align consecutive assignments" and "Align key-value pairs" (for arrays)?

I know this is not strict Laravel style guidelines, but it's a hill I will die on for code I have to work with.  I'm fine with most of the other differences between Laravel and my personal preferences (like I prefer braces on separate lines) as they don't affect my ability to quickly parse what code does, but the aligned assignments do.

**Comment by josefbehr** [comment]
@cheesegrits I added the binary_operators_space option to the pint configuration (see https://mlocati.github.io/php-cs-fixer-configurator/#version:3.14|fixer:binary_operator_spaces), hopefully that is more to your liking. I'm not sure one can achieve exactly what phpstorm does. If you don't like it, keep it as is, it's your code :) You can also add other configurations to pint.json, e.g. to put braces on their own lines.

**Comment by cheesegrits** [comment]
I'm fine with adding Pint and Laravel code style, I've been meaning to do it for a while to all of my projects, just haven't had time to sit down and do it.  Spent a while today adding it to one of the client projects I originally wrote this package for, and figured out the couple of pint.json directives I need to keep me happy, and how to add CI for it.  So I'll go ahead and merge this PR.  Thanks.

**Comment by cheesegrits** [comment]
Ack, this one now has conflicts.  I'm going to close this PR, but add Pint myself.  I spent some time last night figuring out a pint.json for my projects that sticks mostly to the Laravel standard but adds a couple of personal preferences of mine.

Thanks for the PR anyway - the package will get Pint.

**Pull request closed without merging**
