### PR TITLE
Live update Map Widget when getData changes

### PR DESCRIPTION
**Pull request by luttje**
Hi, thanks for the great plugin. I hope I can help with this small PR.

Using v3 I couldn't get the map to update when I made changes in getData. This PR fixes that by listening for the 'update map data' livewire event.

Additionally this reworks the mergeMarkers function in javascript, since that didn't seem to work (it left old markers, since it only checked based on lat and long). Now it checks the id/model_id to see if it needs to update, remove or add markers.

Here's it working in my app:

https://github.com/cheesegrits/filament-google-maps/assets/2738114/6a056ead-a26a-4f25-b3c1-e4c92bde08aa

_The API in the video stores the data in a database table that is retrieved inside `getData`. The changing of the icon is me just editting the code manually to demonstrate it working._

**PS: I wasn't sure if I should fork v3 or v3-alpha, please let me know if I need to move this to a different branch**

### CODE REVIEW

**Comment by cheesegrits** [comment]
@luttje v3 is the correct one.  The v3-alpha branch is specific to the Filament v3-alpha branch (which was Filament v3 but with Livewire V2), which was used by v3 closed beta testers prior to the public Beta being released when Livewire V3 was released.

it's a while since I worked on that merge marker code, but iirc the issue I was trying to solve there was when using "map is filter", where moving and zooming the map changes what is displayed in the table.  Which means I have to "remember" markers which may not be in the getData().  For example, if you zoom in on the map, which removes (filters out) some markers from the table.  Those markers are no longer in the data array coming from the table.  But if you then zoom back out, I need to be able to show them again, so I need to keep them in my internal marker array.

However ... that code isn't really working, and is pretty much WIP.  I need to spend some quality time to figure it out properly.

It's kinda hard to grok your replacement code just looking at it, but it seems your code doesn't take mapIsFilter into account at all?

**Comment by luttje** [comment]
You're right that I didn't take the mapIsFilter into account at all. But your explanation helps me understand what the point is. I'll try make time in a week or so to expand the code and test that mapIsFilter functionality as well

Edit @ 19th of November, adjusting expectations: I'm quite busy so will likely not find time to work on this PR this month. I've got some free time coming up near the end of December that I'll spend on this

**Comment by cheesegrits** [comment]
Cool.  I really welcome any assistance on that.

The aim initially was fairly simple / restricted, and was to support a specific need I had, which was for a "Find a Dealer" type thing.  It doesn't need to support pagination, and the assumption is (kinda) that the initial page load will contain the superset of markers (eg. all of them).  And you can the refine the ones shown in the table by zooming / panning, which kicks off the this.$wire.set("mapFilterIds", ids) in the move() method.  Which will in turn trigger a data update, with just those ID's.  But I don't want to remove any from my internal marker array.  And in theory I could add new markers which weren't in the initial set. if another filter on the table is changed.

It was working in v2, then in v3 it got kinda flaky, bit I haven't had time to dive in a figure it out.

**Comment by luttje** [comment]
I'm struggling getting my PR to play nicely with the filters, zoom, tables etc. I guess what I'm trying to do is a bit too far out of the scope of this project.

I'm going to take a break from this for a while. Perhaps in the coming year I'll find some motivation to re-open a PR with a nicely tested, fully functional live map. Or perhaps I'll create a separate package for that and then open a PR here with new insights.

For now I'll close this PR. Sorry I wasn't of more help, like I hoped to be. Regardless of all that, I wish you all the best!

**Pull request closed without merging**
