### PR TITLE
Added capability to choose map style

### PR DESCRIPTION
**Pull request by Heyian**
I needed to have the map as the satellite view for 1 of my project. So I created this option to choose the style you wish render. I've tested the 4 options (roadmap, satellite, hybrid and terrain) and they work as expected. The default value is still roadmap so the option is optional on the Map field.

### CODE REVIEW

**Comment by ryanmortier** [comment]
@cheesegrits can we merge this please?

**Comment by Heyian** [comment]
Hey there. I've merged this PR onto my fork so we can all get all these goodies from a single place. I gave credits to the person who made the PR in the commits, changelog and in the releases.
I've also credited cheesegrits for his work on the repo and made it clear this was a fork on top of the Readme. I'm not trying to hijack anything, I just want to be able to use all the good solutions people put in the pull requests and I thought I'd made this available to all. If you're interested in this version or want to contribute, you can find my fork at : [Heyian/forkMain](https://github.com/Heyian/filament-google-maps)

I'm open to suggestions on how to move forward from here, simply open up an issue in my fork so we can chat about it.
Thanks.

**Comment by chris-bkjg** [comment]
Why wouldn't you create `type()` instead of your `mapType()`?

`type()` is already available on table columns: https://github.com/cheesegrits/filament-google-maps?tab=readme-ov-file#table-column

**Comment by Heyian** [comment]
You're right, I haven't looked too deeply into this and I don't use the table columns so I never noticed. I'll have a look into it tomorrow or friday. Thanks for the input!

**Comment by cheesegrits** [comment]
I'm working with @Heyian to get this package back up to date.  I had some serious medical issues this year that took me out of circulation.  But I'm back and (more or less) well again.

I'll merge this, but change it from mapType() to type(), to keep it the same as the existing option on the Column.

**Pull request merged**
